### ISSUE TITLE
Current slide selection intermittently jumps (resets) to first slide during show

### ISSUE THREAD

**Issue by zvuc** [tim4724/StagePresenter-for-ProPresenter#2]
Hi, first of all thanks for this great app. Me and the worship team in our church all very like this app over the native stage display included in ProPresenter, especially because you can see much more upcoming lyrics than being able to see just current + adjacent next slide.

One critical problem that prevents us from using StagePresenter over the native stage display was that I noticed the app would randomly jump slide selection to the top whenever I navigate to other slides. When it does, I have to click (activate) the current scene again to have StagePresenter try to return to where it should be at.

I could not find the specific combination of factors that cause this issue — at first I thought if using the "Arrangement" instead of Master view caused trouble with the app properly recognizing order of all slides (since arrangements 'duplicate' slide groups without actually duplicating slides in data?). Also especially because when the StagePresenter view jumps to beginning, the screen fades to a basic view where the slide group labels/colors are not present and only the first 2 slides are visible with a gray outline. (Almost seems like a 'fallback' view where ProPresenter only provides 2 scenes maximum)

But even with arrangement not set (Master), I observed the issue popping up while testing.

One thing that I am almost sure is that the issue occurs much more frequently when I'm using the StagePresenter **over network**. I tried opening StagePresenter on our host machine running ProPresenter 7 and an additional laptop at the same time, and I observed that while the StagePresenter on host machine did not jump the scene, the other one jumped to the beginning.

I'll try to screen capture a video to demonstrate when the issue occurs, but I need to be in church to do that so I'll try doing that when I have the chance 😂

**Comment by tim4724** [comment]
Thanks for creating the issue. 

Just to clarify:

1. A slide in the current presentation is active
2. You click on another slide
3. Stage-Screen reloads with only 2 slides visible (gray outline)
4. Stage-Screen reloads again with the current presentation but presentation is reset (scrolled to the top)

Did I understand the issue correctly?
Does number 3 (when screen reloads with only 2 slides visible) always occur when you experience the issue?

Can you please tell me which version of ProPresenter you are running?

**Comment by zvuc** [comment]
Yes, the steps 3/4 happen almost instantly in succession (Perhaps the fade transition between states make the issue feel more 'longer' to happen) I think I recall sometimes rarely, the StagePresenter would get 'stuck' at step 3 without automatically refreshing to the proper state (although it still resets scroll to the top)

We always keep ProPresenter to the latest version — I remember the last time I updated it was 7.9.2 (I notice 7.10 is out on the website? but not sure if we updated to the version)

**Comment by tim4724** [comment]
Ok 👍 
I already have an idea about the cause for this issue. I will look into it and keep you posted.

**Comment by tim4724** [comment]
I have just published version 0.4.7 with a possible Bug-Fix. @zvuc can you please verify wether the issue is now resolved?

**Comment by zvuc** [comment]
Thanks, I just tried the latest version in our church service today. The sporadic jumping issue seems to have been solved!

I did notice that the slide occassionally does show the 'fallback' screen (only 2 slides, with no slide grouping info) when I change something in the presentation on-the-fly (slide orders, arrangement) but I think that's acceptable. (would be nice if the response time for reflecting the changes were faster, but I guess it would come with its own downsides?)

Thanks for this again!

**Comment by tim4724** [comment]
Good to hear the critical problem is resolved. 👍 

Yes the integration of StagePresenter with ProPresenter is not a 100% seamless at the moment. With version 7.9 (April 2022), ProPresenter got an official public API. I am planning to switch to this new API (hopefully soon), because it looks very very very promising. I expect the integration of StagePresenter with ProPresenter to improve a lot. So stay tuned ;)
