### ISSUE TITLE
StagePresenter screen switches to full-screen slide when activating Background video / Audio tracks

### ISSUE THREAD

**Issue by zvuc** [tim4724/StagePresenter-for-ProPresenter#3]
During recent use, I noticed that when triggering background videos or audio tracks while there is an active slide showing on screen, StagePresenter recognizes it as the main slide being switched, and switches view (fades) to a full-screen slide view of the background video (thumbnail with the play button icon) and title on top.

Since background videos / audio are not displayed on stage display, I think it'd be nice if an exception was made in StagePresenter that it keeps the normal slide view as-is when bg video / audio are triggered.

**Comment by tim4724** [comment]
Thanks for the input. I like the idea.

Version 0.4.8 was just released in the Mac AppStore. With this version the handling of videos and audio tracks was adjusted. There are basically 3 ways to trigger a video, image or audio track:

**1. From the Media section at the bottom in ProPresenter:**
-> The current presentation on the stage screen will not be replaced if a slide is active. However if no slide is active (slide is cleared) the current presentation will be replaced.

**2. From an Item in the playlist at the left in ProPresenter:**
-> The current presentation on the stage screen will always be replaced. 

**3. From a slide in a presentation:**
-> StagePresenter will scroll to that slide. 
Hint: A slide can be disabled in ProPresenter and it then will not be visible on the stage screen. A disabled slide can still be clicked in ProPresenter.

@zvuc What is your experience with StagePresenter version 0.4.8? Does this new behaviour fit your needs or do you expect a different behaviour in a certain situation?
