### ISSUE TITLE
Bible Message not shown

### ISSUE THREAD

**Issue by tim4724** [tim4724/StagePresenter-for-ProPresenter#5]
Version: 7.8.2

It seems working now, I have another problem on stagepresenter it doesn't seem to received or show the Bible message even though I can see it on stage screen I need to move it on a library to show it up

_Originally posted by @armangido in https://github.com/tim4724/StagePresenter-for-ProPresenter/issues/4#issuecomment-1321198633_

**Comment by armangido** [comment]
I can post HTTP data if you want. for this version

**Comment by tim4724** [comment]
Yes please share some details. What do you mean with "I need to move it on a library"? 
Can you please give the steps to reproduce the issue? 

Have you also tried it with the chrome browser on a desktop computer? I haven't tested much with the Android version of chrome...

**Comment by armangido** [comment]
[Video](https://imgur.com/a/Xf0R1FM)

**Comment by armangido** [comment]
`{"acn":"fv","ary":[{"acn":"cs","uid":"ee1e6f0f-7b54-4e28-b1d7-50e9fba7aca7","txt":"5And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day."},{"acn":"csn","uid":"00000000-0000-0000-0000-000000000000","txt":""},{"acn":"ns","uid":"ddafc49f-65da-4590-8d4e-37251b582f51","txt":"6And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters."},{"acn":"nsn","uid":"00000000-0000-0000-0000-000000000000","txt":""},{"acn":"currentRTFNotes","uid":"00000000-0000-0000-0000-000000000000","txt":"{\\rtf0\\ansi\\ansicpg1252{\\fonttbl\\f0\\fnil ArialMT;}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;\\red255\\green255\\blue255;}{\\*\\expandedcolortbl;\\csgenericrgb\\c0\\c0\\c0\\c100000;\\csgenericrgb\\c100000\\c100000\\c100000\\c100000;\\csgenericrgb\\c100000\\c100000\\c100000\\c0;}{\\*\\listtable}{\\*\\listoverridetable}\\uc1\\paperw12240\\margl0\\margr0\\margt0\\margb0\\pard\\li0\\fi0\\ri0\\ql\\sb0\\sa0\\sl240\\slmult1\\slleading0\\f0\\b0\\i0\\ul0\\strike0\\fs100\\expnd0\\expndtw0\\cf1\\strokewidth0\\strokec2\\nosupersub\\ulc0\\highlight3\\cb3}\u0000"},{"acn":"nextRTFNotes","uid":"00000000-0000-0000-0000-000000000000","txt":"{\\rtf0\\ansi\\ansicpg1252{\\fonttbl\\f0\\fnil ArialMT;}{\\colortbl;\\red0\\green0\\blue0;\\red255\\green255\\blue255;\\red255\\green255\\blue255;}{\\*\\expandedcolortbl;\\csgenericrgb\\c0\\c0\\c0\\c100000;\\csgenericrgb\\c100000\\c100000\\c100000\\c100000;\\csgenericrgb\\c100000\\c100000\\c100000\\c0;}{\\*\\listtable}{\\*\\listoverridetable}\\uc1\\paperw12240\\margl0\\margr0\\margt0\\margb0\\pard\\li0\\fi0\\ri0\\ql\\sb0\\sa0\\sl240\\slmult1\\slleading0\\f0\\b0\\i0\\ul0\\strike0\\fs100\\expnd0\\expndtw0\\cf1\\strokewidth0\\strokec2\\nosupersub\\ulc0\\highlight3\\cb3}\u0000"}]}`

**Comment by armangido** [comment]
https://i.imgur.com/GEf9tT7.png
^
When I select a verse in the Bible section that is the one being received
https://i.imgur.com/r0czi8y.png
^
And this one is when I click a slide in a library

**Comment by tim4724** [comment]
Thanks for the videos and images. I will look into it.

**Comment by tim4724** [comment]
The issue seemingly only occurs with ProPresenter running on Windows. I fixed the issue(s) with some workarounds. 
@armangido Can you please test again? A hard refresh in your browser (or clearing the cache) is maybe necessary.

**Comment by armangido** [comment]
Working now on Windows, tried it on safari working, google chrome in android working also, just need to clear cache

**Comment by armangido** [comment]
and additional info, it seems the "Try it on browser" in android and ios seemingly hidden is this intentional? as I needed to navigate manually in URL

**Comment by armangido** [comment]
Have you tried the stage app 2 for pro presenter I have an app for android as I can see there websocket responses are clean, If you want I have it, for you to reverse it?

**Comment by tim4724** [comment]
The Button is hidden depending on the screen size. Which devices did you use? Maybe I should adjust the css media query.

**Comment by armangido** [comment]
> 

Chrome 107.0.5304.91
OS: Android 12; SM-A715F Build/SP1A.210812.016

**Comment by tim4724** [comment]
I have enabled the Button for all devices (all screen sizes). Even tough the welcome and the settings page are not (yet) optimised for mobile use. 
You may need to clear cache again :)

**Comment by armangido** [comment]
Working now Please close this issue, Thanks and God bless!

**Comment by tim4724** [comment]
> Have you tried the stage app 2 for pro presenter I have an app for android as I can see there websocket responses are clean, If you want I have it, for you to reverse it?

Thanks. But at the moment I do not need the "Stage 2" app from ProPresenter. I hope I can soon switch to the new official public API for ProPresenter. This new API looks very promising but is still buggy at the moment.
