### ISSUE TITLE
A button blocking a text

### ISSUE THREAD

**Issue by armangido** [tim4724/StagePresenter-for-ProPresenter#7]
Improvement:  A sidebar for the menu ( Settings, Controller, Close) example, I'm projecting a wide bible texts and some of it are being block by the button which is the Close btw

**Comment by tim4724** [comment]
The "Settings", "Controller" and "Close" buttons are only (supposed to be) visible when the mouse pointer is over the StagePresenter window / screen. When the mouse pointer is moved away, the buttons are invisible again. 

- Do you experience a problem with the buttons not being invisible, when the mouse pointer is moved away?

- If you still think the buttons can be improved, please elaborate more. I am not sure if I understand what you mean. Maybe also share a picture/screenshot. 

Thanks
