### ISSUE TITLE
Intermittent "Cannot read properties of undefined" Error when advancing through slides

### ISSUE THREAD

**Issue by zvuc** [tim4724/StagePresenter-for-ProPresenter#8]
Hi, we've noticed recently that while using StagePresenter we get this error:

![image](https://user-images.githubusercontent.com/2870726/230758709-1186f0ae-b19b-4e17-9db8-fe3f56fc78c9.png)
> An error occurred
> Uncaught TypeError: Cannot read properties of undefined (reading
'presentationName')

As suggested from the error message we've tried looking at the presentations if they have names set properly but that doesn't seem like the problem (the files have proper names as before).

Perhaps it has to do something with the recent ProPresenter update?

**Comment by tim4724** [comment]
Hi @zvuc :)
Yes this is an issue related to the recent ProPresenter Update.
I have just published StagePresenter version 0.4.11 in the AppStore which fixes the issue.

**Comment by zvuc** [comment]
Awesome we'll update the app right away :)
